spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100
        wall:
          enabled: true
        slf4j:
          enabled: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/docs/*,/v2/*" #不统计这些请求数据
        enabled: true
        url-pattern: "/*"
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: gl
        login-password: 123456
        url-pattern: "/druid/*"
        reset-enable: false,
        enabled: true
        allow: ""
      enable: true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.gl: debug